import * as path from 'node:path';
import pc from 'picocolors';
import { log, logError, logWarn } from '../utilities/logger';
import { parseJsonFile } from '../utilities/parse-json';
import type { ResolvedConfig } from './types';
import { flattenKeys } from './flatten-keys';
import { resolveScope } from './resolve-scope';
import type { ResolvedScope } from './resolve-scope';
import type { SyncError } from './validate-sync';
import { validateCrossLanguageSync } from './validate-sync';
import { stampConsumerFiles } from './stamp-consumers';
import { writeOutput } from './write-output';

function printSyncErrors(errors: ReadonlyArray<SyncError>, workspaceRoot: string): void {
  for (const error of errors) {
    if (error.missing.length > 0) {
      logError(`✘ ${error.scope} — missing in ${pc.bold(error.lang)}: ${error.missing.join(', ')}`);
    }
    if (error.orphaned.length > 0) {
      logError(
        `✘ ${error.scope} — orphaned in ${pc.bold(error.lang)}: ${error.orphaned.join(', ')}`,
      );
    }
    log(pc.dim(`  Add to: ${path.relative(workspaceRoot, error.filePath)}`));
  }
}

function printMissingWarnings(errors: ReadonlyArray<SyncError>): void {
  for (const error of errors) {
    if (error.missing.length > 0) {
      logWarn(`⚠ ${error.scope} — ${pc.bold(error.lang)} missing ${error.missing.length} keys`);
      log(pc.dim(`  ${error.missing.join(', ')}`));
    }
  }
}

function printOrphanedErrors(errors: ReadonlyArray<SyncError>, workspaceRoot: string): void {
  for (const error of errors) {
    if (error.orphaned.length > 0) {
      logError(
        `✘ ${error.scope} — orphaned in ${pc.bold(error.lang)}: ${error.orphaned.join(', ')}`,
      );
      log(pc.dim(`  Remove from: ${path.relative(workspaceRoot, error.filePath)}`));
    }
  }
}

function prefixKey(scopeName: string, key: string, separator: string): string {
  return scopeName ? `${scopeName}${separator}${key}` : key;
}

function collectKeys(
  resolvedScopes: ReadonlyArray<ResolvedScope>,
  defaultLang: string,
  separator: string,
  supportedLangs: ReadonlyArray<string>,
  workspaceRoot: string,
  strictSync: boolean,
): { keys: Array<string>; hasErrors: boolean; hasParseErrors: boolean } {
  const keys: Array<string> = [];
  let hasErrors = false;
  let hasParseErrors = false;

  for (const resolved of resolvedScopes) {
    const { errors, hasParseErrors: scopeParseErrors } = validateCrossLanguageSync(
      resolved,
      defaultLang,
      workspaceRoot,
    );

    if (scopeParseErrors) {
      hasParseErrors = true;
      hasErrors = true;
      continue;
    }

    if (errors.length > 0) {
      if (strictSync) {
        printSyncErrors(errors, workspaceRoot);
        hasErrors = true;
        continue;
      }

      printMissingWarnings(errors);

      if (errors.some((syncError) => syncError.orphaned.length > 0)) {
        printOrphanedErrors(errors, workspaceRoot);
        hasErrors = true;
      }
    }

    if (errors.length === 0) {
      const langsLabel = supportedLangs.join(', ');
      log(`${pc.green('✔')} ${resolved.name || '(root)'} ${pc.dim(`(${langsLabel} synced)`)}`);
    }

    const defaultLangFile = resolved.files.get(defaultLang);
    if (!defaultLangFile) {
      hasErrors = true;
      continue;
    }

    const json = parseJsonFile(defaultLangFile, workspaceRoot);
    if (!json) {
      hasParseErrors = true;
      hasErrors = true;
      continue;
    }

    keys.push(...flattenKeys(json, '').map((k) => prefixKey(resolved.name, k, separator)));
  }

  return { keys, hasErrors, hasParseErrors };
}

const HEADER = '// This file is auto-generated by i18n-keygen. Do not edit.\n\n';

function hashKeys(keys: ReadonlyArray<string>): string {
  const str = keys.join('\n');
  let hash = 5381;
  for (let i = 0; i < str.length; i++) {
    hash = ((hash << 5) + hash + str.charCodeAt(i)) | 0;
  }
  return (hash >>> 0).toString(36);
}

function formatOutput(keys: ReadonlyArray<string>): string {
  if (keys.length === 0) {
    return `${HEADER}export type I18nKey = never;\n`;
  }
  const unionMembers = keys.map((key) => `  | '${key}'`).join('\n');
  return `${HEADER}export type I18nKey =\n${unionMembers};\n`;
}

export function generate(workspaceRoot: string, options: ResolvedConfig): boolean {
  const resolvedScopes = options.scopes
    .map((scope) => resolveScope(workspaceRoot, scope, options.supportedLangs))
    .sort((a, b) => a.name.localeCompare(b.name));

  const scopeNames = resolvedScopes.map((s) => s.name || '(root)').join(', ');
  log(`Found ${pc.bold(String(resolvedScopes.length))} scopes: ${scopeNames}`);

  const { keys, hasErrors, hasParseErrors } = collectKeys(
    resolvedScopes,
    options.defaultLang,
    options.scopeSeparator,
    options.supportedLangs,
    workspaceRoot,
    options.strictSync,
  );

  const outputFile = path.resolve(workspaceRoot, options.outputFile);

  if (hasParseErrors) {
    logWarn('⏳ Skipping write — unreadable file detected (file may be mid-save)');
    return false;
  }

  writeOutput(outputFile, formatOutput(keys), keys.length, workspaceRoot);
  stampConsumerFiles(outputFile, hashKeys(keys), options.stampConsumer);

  return !hasErrors;
}
