// This file is auto-generated by i18n-keygen. Do not edit.

export type I18nKey =
  | 'core.appTitle'
  | 'core.nav.home'
  | 'core.nav.products'
  | 'core.nav.orders'
  | 'core.dialog.cancel'
  | 'core.dialog.confirm'
  | 'orders.pageTitle'
  | 'orders.status.pending'
  | 'orders.status.shipped'
  | 'orders.status.delivered'
  | 'orders.actions.cancel'
  | 'orders.actions.track'
  | 'products.pageTitle'
  | 'products.table.name'
  | 'products.table.price'
  | 'products.table.actions'
  | 'products.emptyState';
